### ISSUE TITLE
AuthState.isAuthenticated is not getting updated on token expiry.

### ISSUE THREAD

**Issue by singh-param-veer** [okta/okta-auth-js#1047]
Version: 5.9.0

Steps to reproduce:

- Login to the app (assuming that autoRenew option is enabled)
- Wait for token to expire, but change "Throttling state" to "Offline" (if using Chrome, alternatively just turn off internet connection) few seconds before expiry time
- Renewing request will fail with "AuthApiError" ("Failed to fetch" message), but error will not be emitted.
- Switch "Throttling state" back to "No throttling"
- Since token has expired, backend API calls will return 401 but authState.isAuthenticated will remain true; also there is no token refresh calls to /token endpoint after switching the internet ON.

Observations:
- If token is about to expire, it tries to refresh token (few seconds before the actual expiry time) and update auth token only once.

Similar Issue is reported here: [AuthApiError silently ignored if caused by network failure with autoRenew enabled](https://github.com/okta/okta-auth-js/issues/987)

**Comment by aarongranick-okta** [comment]
@singh-param-veer It does sounds like your issue is very similar to the one linked. I see that a fix for that issue has been merged to the main branch but has not been released on NPM/CDN yet. The fix will be part of the `5.10.0` release which should occur this week. Hopefully that should resolve this issue!

**Comment by singh-param-veer** [comment]
Hi @aarongranick-okta , we tried cloning and linking the master code (commit hash: 6a38bb2e49600cd81e93a14e6080b1b0d2da24e9) of okta-auth-js and we are still facing same issue.

**Comment by denysoblohin-okta** [comment]
Thanks for submitting this issue.
Internal ref:  OKTA-460081

**Comment by singh-param-veer** [comment]
Hi @denysoblohin-okta,
Is the above issue fixed in [6.1.0](https://github.com/okta/okta-auth-js/releases/tag/okta-auth-js-6.1.0) ? 
Could you please provide us an update here?

**Comment by singh-param-veer** [comment]
Hi @denysoblohin-okta , have added 1 comment on the token removal.

https://github.com/okta/okta-auth-js/pull/1087
Please look at it when you get a chance.
