### ISSUE TITLE
Auth JS 6.4.0 causes issues in Angular apps when testing

### ISSUE THREAD

**Issue by mraible** [okta/okta-auth-js#1174]
### Describe the bug?

Today I discovered that if you upgrade an Angular app from using Auth JS 6.2.0 from 6.4.0, there are stack traces when you run `npm test`:

```
ERROR: 'Unhandled Promise rejection:', 'Failed to execute 'postMessage' on 'BroadcastChannel': Channel is closed', '; Zone:', '<root>', '; Task:', 'Promise.then', '; Value:', DOMException{stack: 'Error: Failed to execute 'postMessage' on 'BroadcastChannel': Channel is closed
    at Object.postMessage (http://localhost:9876/_karma_webpack_/webpack:/node_modules/broadcast-channel/dist/esbrowser/methods/native.js:26:1)
    at http://localhost:9876/_karma_webpack_/webpack:/node_modules/broadcast-channel/dist/esbrowser/broadcast-channel.js:198:1
    at _ZoneDelegate.invoke (http://localhost:9876/_karma_webpack_/webpack:/node_modules/zone.js/fesm2015/zone.js:372:1)
    at ProxyZoneSpec.onInvoke (http://localhost:9876/_karma_webpack_/webpack:/node_modules/zone.js/fesm2015/zone-testing.js:287:1)
    at _ZoneDelegate.invoke (http://localhost:9876/_karma_webpack_/webpack:/node_modules/zone.js/fesm2015/zone.js:371:1)
    at Zone.run (http://localhost:9876/_karma_webpack_/webpack:/node_modules/zone.js/fesm2015/zone.js:134:1)
    at http://localhost:9876/_karma_webpack_/webpack:/node_modules/zone.js/fesm2015/zone.js:1275:1
    at _ZoneDelegate.invokeTask (http://localhost:9876/_karma_webpack_/webpack:/node_modules/zone.js/fesm2015/zone.js:406:1)
    at ProxyZoneSpec.onInvokeTask (http://localhost:9876/_karma_webpack_/webpack:/node_modules/zone.js/fesm2015/zone-testing.js:318:1)
    at _ZoneDelegate.invokeTask (http://localhost:9876/_karma_webpack_/webpack:/node_modules/zone.js/fesm2015/zone.js:405:1)'}, 'Error: Failed to execute 'postMessage' on 'BroadcastChannel': Channel is closed
    at Object.postMessage (http://localhost:9876/_karma_webpack_/webpack:/node_modules/broadcast-channel/dist/esbrowser/methods/native.js:26:1)
    at http://localhost:9876/_karma_webpack_/webpack:/node_modules/broadcast-channel/dist/esbrowser/broadcast-channel.js:198:1
    at _ZoneDelegate.invoke (http://localhost:9876/_karma_webpack_/webpack:/node_modules/zone.js/fesm2015/zone.js:372:1)
    at ProxyZoneSpec.onInvoke (http://localhost:9876/_karma_webpack_/webpack:/node_modules/zone.js/fesm2015/zone-testing.js:287:1)
    at _ZoneDelegate.invoke (http://localhost:9876/_karma_webpack_/webpack:/node_modules/zone.js/fesm2015/zone.js:371:1)
    at Zone.run (http://localhost:9876/_karma_webpack_/webpack:/node_modules/zone.js/fesm2015/zone.js:134:1)
    at http://localhost:9876/_karma_webpack_/webpack:/node_modules/zone.js/fesm2015/zone.js:1275:1
    at _ZoneDelegate.invokeTask (http://localhost:9876/_karma_webpack_/webpack:/node_modules/zone.js/fesm2015/zone.js:406:1)
    at ProxyZoneSpec.onInvokeTask (http://localhost:9876/_karma_webpack_/webpack:/node_modules/zone.js/fesm2015/zone-testing.js:318:1)
    at _ZoneDelegate.invokeTask (http://localhost:9876/_karma_webpack_/webpack:/node_modules/zone.js/fesm2015/zone.js:405:1)'
```

If I revert to Auth JS 6.2.0, the problem goes away.

### What is expected to happen?

<img width="1442" alt="Screen Shot 2022-04-11 at 14 29 38" src="https://user-images.githubusercontent.com/17892/162826559-6366215c-25e4-4345-a1b1-4e715b0ac1d9.png">

### What is the actual behavior?

<img width="1442" alt="Screen Shot 2022-04-11 at 14 28 55" src="https://user-images.githubusercontent.com/17892/162826589-9fee118f-f7d4-4d1d-a6d4-b3be71dc45a5.png">

### Reproduction Steps?

```
git clone https://github.com/okta-samples/okta-angular-sample.git
cd okta-angular-sample
npm i && npm test
```

There's no stack trace because v6.2.0 is used. Update `package.json` to use `"@okta/okta-auth-js": "^6.4.0"` and try again.

```
npm i
npm test
````

You'll see the stack trace, even though tests pass.

### SDK Versions

Everything works great with:

```json
"@okta/okta-angular": "^5.1.1",
"@okta/okta-auth-js": "^6.2.0",
```

### Execution Environment

```
$ node --version
v16.14.0
```

macOS Monterey

**Comment by mraible** [comment]
This seems to happen on the Vue sample as well. However, it’s in the browser console for Vue, and downgrading to Auth JS 6.2.0 doesn’t make it go away.

<img width="1146" alt="Screen Shot 2022-04-11 at 15 19 10" src="https://user-images.githubusercontent.com/17892/162835666-3f661be9-54d0-4b8b-b2a3-52d054c97c20.png">

Steps to reproduce:

1. Install the [Okta CLI](https://cli.okta.com) and configure it with your org.
2. Run `okta start vue` and follow the printed instructions.
3. Run `npm start` and you'll see the errors in your browser console.

**Comment by mraible** [comment]
This doesn't just happen in Chrome. It happens in Firefox and Safari too.

<img width="1102" alt="Screen Shot 2022-04-11 at 15 27 10" src="https://user-images.githubusercontent.com/17892/162836389-b5d25c7f-9b29-4a38-994f-0ab2a9e79e5b.png">
<img width="1092" alt="Screen Shot 2022-04-11 at 15 27 13" src="https://user-images.githubusercontent.com/17892/162836399-2d59d434-09c3-4901-a167-d62872f13e0f.png">

**Comment by jaredperreault-okta** [comment]
@mraible Do you know what version of `broadcast-channel` is being used in your builds?

`yarn why broadcast-channel` should do the trick

**Comment by mraible** [comment]
@jaredperreault-okta I'm not using yarn, I'm using npm. I'm not sure if `npm list` is the same, but I tried `npm list broadcast-channel` in the Angular sample:

```
$ npm list broadcast-channel
okta-angular-sample@0.0.0 /Users/mraible/dev/okta-samples/okta-angular-sample
└─┬ @okta/okta-auth-js@6.4.0
  └── broadcast-channel@4.10.0
```

If I try it in the Vue sample, it's a similar result:

```
okta-vue-sample@1.0.0 /Users/mraible/dev/okta-samples/okta-vue-sample
└─┬ @okta/okta-auth-js@6.4.0
  └── broadcast-channel@4.10.0
```

**Comment by saosebastiao** [comment]
This is happening in Okta-React as well. Is there a workaround?

**Comment by jaredperreault-okta** [comment]
@saosebastiao are you able to reproduce this with the [Okta React Sample](https://github.com/okta/samples-js-react)?

What version of `@okta/okta-auth-js` and `@okta/okta-react` are you using?

**Comment by shuowu** [comment]
Fixed in [6.4.1](https://github.com/okta/okta-auth-js/issues/1174)

**Comment by mraible** [comment]
I just tried validating everything is fixed using the [okta-angular-sample](https://github.com/okta-samples/okta-angular-sample). If I upgrade it to use Auth JS 6.4.2, the problem does go away. 

<img width="1442" alt="Screen Shot 2022-04-18 at 10 00 12" src="https://user-images.githubusercontent.com/17892/163836372-47bff338-6657-4c70-9e3c-3bcce5d9e7ad.png">

However, if I upgrade the [okta-vue-sample](https://github.com/okta-samples/okta-vue-sample) to 6.4.2, there are still errors in my browser's console.

<img width="1227" alt="Screen Shot 2022-04-18 at 09 58 24" src="https://user-images.githubusercontent.com/17892/163836503-990b33a4-5b1c-4306-a858-7de1035c8acc.png">

**Comment by mraible** [comment]
I see something similar in the [Okta CLI's React sample](https://github.com/okta-samples/okta-react-sample/pull/113):

```
FAIL src/App.test.jsx
  ✕ renders title link (250 ms)

  ● renders title link

    No useable method found in ["native","idb","localstorage"]

      at node_modules/@okta/okta-auth-js/dist/webpack:/OktaAuth/node_modules/broadcast-channel/dist/esbrowser/method-chooser.js:[42](https://github.com/okta-samples/okta-react-sample/runs/6067863436?check_suite_focus=true#step:7:42):25
      at new he (node_modules/@okta/okta-auth-js/dist/webpack:/OktaAuth/node_modules/broadcast-channel/dist/esbrowser/broadcast-channel.js:22:17)
```

By "similar", I mean `broadcast-channel` is in the stack trace. I tried upgrading to Auth JS 6.4.3, but it does not solve this issue.

**Comment by StephenAtCFA** [comment]
We're also seeing this in 6.4.3 when using react.

**Comment by jaredperreault-okta** [comment]
@StephenAtCFA can you provide more details?

You're seeing this error in your application itself, or in testing (jest or otherwise)?

What versions of the other relevant modules are you using, ie React, okta-react?

Do you see this same behavior in different versions of okta-auth-js?

**Comment by mrcotter** [comment]
Seeing the same error messages in the latest `6.4.3` version with my Vue 3 application using `okta-auth-js` and `okta-signin-widget`.

Downgrade `okta-auth-js` and lock its version to `6.2.0` works but any other new versions have similar problem.

**Comment by jaredperreault-okta** [comment]
@mrcotter What browser/OS are you testing this on? I am currently unable to repro this issue (using okta-auth-js 6.4.3)

**Comment by StephenAtCFA** [comment]
On brave v 1.36.122 / mac os 12.3 / node 16.14.0 / react 17.0.2 / webpack 5.70.0 / @babel/core 7.17.8 / okta-react 6.4.3 / okta-auth-js 6.4.3

**Comment by StephenAtCFA** [comment]
Using redirect not okta widget

**Comment by mrcotter** [comment]
> @mrcotter What browser/OS are you testing this on? I am currently unable to repro this issue (using okta-auth-js 6.4.3)

On latest versions of Chrome (100.0.4896.88) and Firefox (99.0.1) on macOS (12.3.1)

An example from the browser console:

![Screen Shot 2022-04-20 at 10 00 13](https://user-images.githubusercontent.com/5259084/164120620-87ec89a8-a2b1-47f2-b91c-46152d94b75e.png)

**Comment by mraible** [comment]
I tried upgrading the Okta CLI's Vue sample to [okta-auth-js@6.5.0](https://github.com/okta-samples/okta-vue-sample/pull/251) today and there are still errors in my console.

<img width="1309" alt="Screen Shot 2022-05-02 at 12 15 10" src="https://user-images.githubusercontent.com/17892/166302320-9fe77221-74fc-4a1f-a4e5-908ed9b25696.png">
.

**Comment by pzi** [comment]
After login and when navigating a next.js app with v6.5.0 and okta-react v6.4.3

<img width="957" alt="image" src="https://user-images.githubusercontent.com/2037851/166634113-bb13bd74-357d-4a02-ba44-4c4916720509.png">

**Comment by richmason** [comment]
I'm seeing this issue in my Vue 3 project which is using @okta/okta-auth-js v6.5.1 and @okta/okta-vue v5.2.1:
![CleanShot 2022-05-26 at 19 10 38](https://user-images.githubusercontent.com/330359/170476860-243c1d53-d94d-4993-80b5-eb86be1596ff.png)

**Comment by TD-DO** [comment]
I am seeing this in my React project:
    "@okta/okta-auth-js": "^6.6.1",
    "@okta/okta-react": "^6.4.3",
    "@okta/okta-signin-widget": "^6.4.0",
Is there an ETA on when this may be fixed?

**Comment by TD-DO** [comment]
Downgrading to 6.1.0 works

**Comment by jaredperreault-okta** [comment]
`okta-react` 6.5.0 and `okta-vue` 5.3.0 were released this morning and address this issue

cc @pzi @richmason @TD-DO

**Comment by jaredperreault-okta** [comment]
Thank you for the stack traces, but can you provide a code snippet as well? Perhaps from your `ReportCards` component (since it mentioned in the stack trace). At this time I cannot reproduce this issue

**Comment by pzi** [comment]
> `okta-react` 6.5.0 and `okta-vue` 5.3.0 were released this morning and address this issue
> 
> cc @pzi @richmason @TD-DO

Preliminary testing with our Next.js app seems to agree :) Thanks for getting this fixed. Now we just need to get [the M1 issue addressed](https://github.com/okta/okta-auth-js/issues/1256), so everyone can build the app.

**Comment by KLCarrierDirect** [comment]
> Thank you for the stack traces, but can you provide a code snippet as well? Perhaps from your `ReportCards` component (since it's mentioned in the stack trace). At this time I cannot reproduce this issue

`import React, { useEffect, useState } from "react"
import Card from "@mui/material/Card"
import Grid from "@mui/material/Grid"
import Typography from "@mui/material/Typography"
import { makeStyles } from "@mui/styles"
import { useOktaAuth } from "@okta/okta-react"
import { getAdminDashReportsByReportType } from "../../adapters/moesif"

const useStyles = makeStyles((theme) => ({
    card: {
        width: "100%",
        height: 675,
        padding: "20px 20px 20px 20px",
    },
}))
const ReportsCard = ({ theme, reportType, index }) => {
    const classes = useStyles()
    const { authState } = useOktaAuth()
    const [isLoaded, setIsLoaded] = useState(false)
    const [report, setReport] = useState()

    const token = authState?.accessToken?.accessToken

    const hideSpinner = () => setIsLoaded(true)

    useEffect(() => {
        let fetchReport

        try {
            fetchReport = async () => {
                const result = await getAdminDashReportsByReportType(
                    token,
                    reportType
                )
                setReport(result.data.reports[0])
                setIsLoaded(true)
            }

            fetchReport()
        } catch (err) {
            console.error(err)
            fetchReport = async () => {
                const result = await getAdminDashReportsByReportType(
                    token,
                    reportType
                )
                setReport(result.data.reports[0])
                setIsLoaded(true)
            }

            fetchReport()
        }
    }, [])

    return (
        <Grid item container xs={6} key={index}>
            <Card
                elevation={6}
                className={classes.card}
                // sx={{
                //     border: 1,
                //     borderColor: theme.palette.primary.dark,
                // }}
            >
                {!isLoaded ? (
                    <Grid item container zIndex={9999} justifyContent="center">
                        <Grid
                            item
                            container
                            mt="11%"
                            position="absolute"
                            justifyContent="center"
                            direction="column"
                        >
                            <Grid item justifyContent="center">
                                <Typography
                                    textAlign="center"
                                    color="#272f33"
                                    fontSize="24px"
                                >
                                    Loading. . .
                                </Typography>
                            </Grid>
                        </Grid>
                    </Grid>
                ) : null}
                {isLoaded ? (
                    <iframe
                        id={reportType}
                        src={`${report.url}&primary_color=%23396a6a&color_array=%23E37A41%2C%23396a6a%2C%23302E2C%2C%23777B83%2C%23A8A8A9&chart_font_color=%23396a6a`}
                        name={reportType}
                        frameBorder="0"
                        noresize="noresize"
                        width="100%"
                        height="100%"
                        // scrolling="no"
                        onLoad={() => hideSpinner()}
                    />
                ) : null}
            </Card>
        </Grid>
    )
}

export default ReportsCard`

---

Please let me know if this helps or if you need another code snippet. I am having difficulty replicating this issue on js fiddle.

**Comment by jaredperreault-okta** [comment]
@KLCarrierDirect 

Can you try upgrading auth-js to `6.7`? `6.7` includes a fix for the `channel is closed` error ([CHANGELOG](https://github.com/okta/okta-auth-js/blob/master/CHANGELOG.md#features))

I also recommend fetching tokens directly from the `tokenManager` rather than `authState`. Recently we have observed an issue with tokens on `authState`, we believe due to the async nature of token refresh (`authState` updates are slightly delayed) and we plan to remove tokens from the `authState` in the next major version

```
const ReportsCard = ({ theme, reportType, index }) => {
    const classes = useStyles()
    const { oktaAuth } = useOktaAuth()
    const [isLoaded, setIsLoaded] = useState(false)
    const [report, setReport] = useState()

    const hideSpinner = () => setIsLoaded(true)

    useEffect(() => {
        let fetchReport

        try {
            fetchReport = async () => {
                const token = await oktaAuth.tokenManager.get('accessToken');
                const result = await getAdminDashReportsByReportType(
                    token,
                    reportType
                )
                setReport(result.data.reports[0])
                setIsLoaded(true)
            }
```

**Comment by KLCarrierDirect** [comment]
@jaredperreault-okta 

Thank you so much, upgrading to `@okta/okta-auth-js 6.7.0` successfully removed the Broadcast channel errors from the console. 
I will apply your recommendation to use the `tokenManager` as we did notice issues with our tokens when upgrading `@okta/okta-react`.

**Comment by jaredperreault-okta** [comment]
Closing this issue since the original report of the `channel is closed` error has been fixed in auth-js `6.7`

A few other discussions have spawned on this thread, please open tickets if you need additional assistance
