### ISSUE TITLE
AuthSdkError: Unable to retrieve OAuth redirect params from storage

### ISSUE THREAD

**Issue by RandScullard** [okta/okta-auth-js#488]
I am running the samples-js-react/custom-login sample. With version 3.2.3 of okta-auth-js installed (as a dependency of @okta/okta-react@3.0.7), this sample works fine. Today, I uninstalled and reinstalled @okta/okta-react@3.0.7 and as a result, my copy of okta-auth-js was upgraded from 3.2.3 to 3.2.4. Now when I log in, the login redirects to /implicit/callback, which displays the error: `AuthSdkError: Unable to retrieve OAuth redirect params from storage`

In devtools, I can see that the `okta-oauth-redirect-params` cookie is still being set, but it looks like the code in token.js has been changed to look for the redirect params in local storage rather than the cookie -- and there is nothing in local storage by that name. I have cleared my site storage, so I know none of this is left over from the old version.

I then forced npm to downgrade from okta-auth-js@3.2.4 back to 3.2.3 and now everything works again.

**Comment by shuowu** [comment]
@RandScullard Thanks for reporting the issue! Looks like the `okta-signin-widget` that responsible for custom-login has not be updated with the latest patch. It stored redirect params in cookie, but okta-react was trying to get the params from sessionStorage.

Internal Ref: OKTA-332863

**Comment by Joyeeta** [comment]
I am facing a similar issue. I am using "@okta/okta-signin-widget": "^3.8.2" and "@okta/okta-angular": "^2.0.0", which has a dependency "okta-auth-js": 3.2.4. I have specified storage as 'localStorage' while initializing "OktaAuth" ,
const athClient = new OktaAuth({
        url: 'XXX',
        redirectUri: redirectUri,
        responseMode: 'query',
        pkce: true,
        tokenManager: {
          storage: 'localStorage',
          expireEarlySeconds: 300
        }
      });
While debugging,i noticed in token.js it is trying to read the `okta-oauth-redirect-params`  from the sessionStorage rather than localStorage. As a result, the login redirects to /implicit/callback, which displays the error: `AuthSdkError: Unable to retrieve OAuth redirect params from storage`.

Has anybody else faced the issue? If yes, could you please help.

**Comment by TaylorNoelJordan** [comment]
I'm having the same issue as @Joyeeta and would love some insight.

**Comment by aarongranick-okta** [comment]
@TaylorNoelJordan We have identified the flaw and rae currently testing a fix for this issue.

**Comment by aarongranick-okta** [comment]
@TaylorNoelJordan We have released a new version, 3.2.5, which should correct this flaw

**Comment by TaylorNoelJordan** [comment]
@aarongranick-okta I'm only seeing version 4.0.2 - where would I find 3.2.5? https://www.npmjs.com/package/@okta/okta-auth-js

**Comment by aarongranick-okta** [comment]
> @aarongranick-okta I'm only seeing version 4.0.2 - where would I find 3.2.5? https://www.npmjs.com/package/@okta/okta-auth-js

If you click "versions" you can see all published versions. We released 3.2.5 and 4.0.2 yesterday. okta-react wants version 3.2 so 3.2.5 should install automatically on a fresh install

**Comment by TaylorNoelJordan** [comment]
@aarongranick-okta thank you! Which version is required for okta/okta-angular?

**Comment by isemona** [comment]
@TaylorNoelJordan 3.2.5 as well @aarongranick-okta recommends reinstalling node_modules again.

**Comment by isemona** [comment]
@TaylorNoelJordan version 3.2.5 @aarongranick-okta recommends reinstalling node_modules again

**Comment by ra-hulk** [comment]
Hi @aarongranick-okta, I am still getting this error. Please see specifics:

- Browser - Microsoft Edge 44.17763.831.0 (Microsoft EdgeHTML 18.17763). I am also using `text-encoding` npm package for polyfills, (as specified in Okta documentation [here](https://github.com/okta/okta-auth-js#pkce-oauth-20-flow).
- Create react App with `@okta/okta-react@3.0.8`, which installs `@okta/okta-auth-js@3.2.5` as its dependency.

**Comment by IraErshova** [comment]
Hi! I have the same issue. I'm using:
```
@okta/okta-angular: 2.2.0 
@okta/okta-auth-js: 3.2.5 
@okta/okta-signin-widget: 4.4.4 
```
also I've tried to use latest versions:
```
@okta/okta-angular: 2.2.1
@okta/okta-auth-js: 4.0.2
@okta/okta-signin-widget: 4.5.1
```
I use widget and OktaCallbackComponent as redirect component. Get these error:
`AuthSdkError: Unable to retrieve OAuth redirect params from storage`

**Comment by IraErshova** [comment]
I've found a workaround for my Angular app with okta widget. Instead of using OktaCallbackComponent I use my own component.  I added this code on initialization:
```
import { REDIRECT_OAUTH_PARAMS_NAME } from '@okta/okta-auth-js';

ngOnInit(): void {
    // NOTE: workaround to avoid AuthSdkError: Unable to retrieve OAuth redirect params from storage error
    const redirectParams = this.cookieService.get(REDIRECT_OAUTH_PARAMS_NAME);
    window.sessionStorage.setItem(REDIRECT_OAUTH_PARAMS_NAME, redirectParams);
    this.oktaAuth.handleAuthentication().then(() => {
        this.router.navigate(['/']); // to home page
    }).catch(error => {
        // handle error
    });
  }
```

And everything works fine.

After debugging okta functionality I found out that it looks for **REDIRECT_OAUTH_PARAMS_NAME** in **sessionStorage** but this property is set up in **cookie**. I hope this problem will be fixed in future

**Comment by TaylorNoelJordan** [comment]
@IraErshova where does 'cookieService' come from?

**Comment by IraErshova** [comment]
> @IraErshova where does 'cookieService' come from?

@TaylorNoelJordan It's just my service to work with cookie - you can replace it with your own or use **document.cookie** directly

**Comment by DavidLozzi** [comment]
I'm getting the same issues, seems more prevalent since we moved to a custom tokenManager for saving to cookies, and almost always happens in IE11 (yuck I know).

Looking at this library's code, however, it appears unrelated to where we store the tokens. It [sets](https://github.com/okta/okta-auth-js/blob/e70b8c0b1af1823330240a20c07e052f4918e0d1/lib/token.ts#L663) the `REDIRECT_OAUTH_PARAMS_NAME` to session storage if the browser supports it, otherwise uses the cookie. Then [gets](https://github.com/okta/okta-auth-js/blob/e70b8c0b1af1823330240a20c07e052f4918e0d1/lib/token.ts#L774) it from session storage if it's available, otherwise the cookie.

If I'm reading this right, this error could happen if it sets to one and tries to get from the other (or it never sets, but assuming it does since @IraErshova workaround works).

The getter might be better served to be a `try` instead of an `if`? Something like 

```
function getOAuthParamsStrFromStorage(sdk) {
  let oauthParamsStr;
  try {
    const storage = browserStorage.getSessionStorage();
    oauthParamsStr = storage.getItem(REDIRECT_OAUTH_PARAMS_NAME);
    storage.removeItem(REDIRECT_OAUTH_PARAMS_NAME);
    return oauthParamsStr;
  } catch {
    try {
      oauthParamsStr = cookies.get(REDIRECT_OAUTH_PARAMS_NAME);
      cookies.delete(REDIRECT_OAUTH_PARAMS_NAME);
      return oauthParamsStr;
    } catch {
      return null;
    }
  }
}
```

**Comment by aarongranick-okta** [comment]
@DavidLozzi The `REDIRECT_OAUTH_PARAMS_NAME` should be unrelated to anything involving the token manager. We have reports that IE11, in certain modes, will clear session storage when doing a redirect. However it should be able to fallback to using cookies.  Make sure that you are using the latest version of `okta-auth-js` as we have released some fixes for this logic. If you are using an SDK like `okta-angular` or `okta-react`, you may need to wipe your node_modules and any `.lock` files to install the latest version.

**Comment by DavidLozzi** [comment]
@aarongranick-okta agreed, I thought it was related but determined it's unrelated. We just deployed the latest from 3.0.4 to 3.0.8 and am now seeing these issues. Our deployment servers clear node_modules every build, so we're using all the latest. We're now rolling back to .4 due to this issue. 

See my proposed code above, wouldn't something like that work better, try one and then try the next instead of a solid condition?

**Comment by DavidLozzi** [comment]
> Make sure that you are using the latest version of `okta-auth-js` as we have released some fixes for this logic. If you are using an SDK like `okta-angular` or `okta-react`, you may need to wipe your node_modules and any `.lock` files to install the latest version.

@aarongranick-okta am I reading the [oidc repo right](https://github.com/okta/okta-oidc-js/blob/01a2fe3caf7f2ac173057b1e315717603f3d1e05/packages/okta-react/package.json#L37), is the react library using `"@okta/okta-auth-js": "^3.2.3",`? It looks like `okta-auth-js` is on v4+ now. Are you assuming react is using the latest version?

**Comment by aarongranick-okta** [comment]
@DavidLozzi We have not released a new version of `okta-react` against `okta-auth-js@4` yet, but it is very close to release. 

The logic for 3.2 is here: https://github.com/okta/okta-auth-js/blob/3.2/packages/okta-auth-js/lib/token.js#L621

We also have a PR ready for 3.2 which may fix this issue: https://github.com/okta/okta-auth-js/pull/517/files#diff-6d41d03b58c740b8c9f6d7c1ba363f4c6352f0b653c9771de9259765d1677560R621

Currently we write to session storage if it is enabled, and only write to cookie if session storage is disabled. However, in the case of IE 11 I think the problem may not be that session storage is disabled, but that it gets **cleared** when redirecting to Okta. This PR changes the logic to write to both cookie and session storage unconditionally.

One way to avoid this whole problem with the OAUTH_PARAMS would be to not redirect. We have a sample here that shows how you can embed the signin widget into your app and retrieve tokens without any redirect to Okta: https://github.com/okta/samples-js-react/blob/master/custom-login/src/Login.jsx#L40

You can embed the widget in your app using NPM or include a script from our CDN. The only (minor) downside of this approach is that by using a specific version of the widget you will have to manually update to newer versions in the future to get new features. Redirecting to Okta will always use the latest widget version, because it is hosted on our site. I believe most customers prefer the embedded widget with no redirect because it is a better user experience.

https://github.com/okta/okta-signin-widget#getting-started

**Comment by DavidLozzi** [comment]
@aarongranick-okta thanks for the details, when do we think the PR for 3.2 will be ready for consumption? That fix looks promising!

**Comment by aarongranick-okta** [comment]
@DavidLozzi We have released version 3.2.6 and 4.0.3 which contain the fix.

**Comment by DavidLozzi** [comment]
@aarongranick-okta is this included in the React library as well? I see that's still on 3.0.8

**Comment by shuowu** [comment]
@DavidLozzi It's patch fix for `okta-auth-js`. A brand new installation of `node_modules` should use the `@okta/okta-auth-js@3.2.6` in `okta-react`.

**Comment by estorski** [comment]
Seems like the issue is still present with `@ukta/ukta-auth-js@3.2.6`, at least I was unable to make it work. Does anybody have it fixed?

**Comment by shuowu** [comment]
@estorski Can you share simple reproduction steps and the browser env?

**Comment by estorski** [comment]
@shuowu sure thing.

**Browser:** Internet Explorer 11.1082.18362.0, update version 11.0.210
**Libs:** `"@okta/okta-auth-js": "3.2.6"`, `"@okta/okta-react": "3.0.8"`
**Repro steps:** 
* use PKCE auth flow with OKTA-hosted login page
* try to access protected resource
* get redirected to the login page
* put the creds in place, submit them and get them successfully validated
* get redirected back to the SPA's login callback page where you try to perform `handleAuthentication`
* get error saying `Unable to retrieve OAuth redirect params from storage`

In other browsers everything works as expected.

**Comment by shuowu** [comment]
@estorski As the new `okta-auth-js@3.2.6` patch handles `redirect params` in both cookie and sessionStorage, it should be able to find the params after redirection.

I would suggest clearing your `node_modules`, lock file, and npm cache, then try a re-install the modules.

If the issue still persists after reinstallation, please reach out to our support team (developers@okta.com) for better information and feedback collection.

**Comment by DavidLozzi** [comment]
@shuowu i just ran through it all, confirmed package-lock has the latest:

```
    "@okta/configuration-validation": {
      "version": "0.4.3",
      "resolved": "https://nexus.tooling.smp-paas.com/repository/npm-group/@okta/configuration-validation/-/configuration-validation-0.4.3.tgz",
      "integrity": "sha512-dn/1EMGhwajQwV/jNIrj6zvYDdDpFIQnrdqRAww/SvzIz9cuPbw1vYBRpBYX2RQpPhJJuy6iZf0XB6yWVDUavw==",
      "requires": {
        "lodash": "^4.17.15"
      }
    },
    "@okta/okta-auth-js": {
      "version": "3.2.6",
      "resolved": "https://nexus.tooling.smp-paas.com/repository/npm-group/@okta/okta-auth-js/-/okta-auth-js-3.2.6.tgz",
      "integrity": "sha512-4N3XkaHUs2QbUR3ymg+PtoPAGluU3IkBK1kIfoYWeONXTyz0v/PpAKgHDe3RJkvRkDQzvAJDdT6VL29wIYE1ww==",
      "requires": {
        "Base64": "0.3.0",
        "cross-fetch": "^3.0.0",
        "js-cookie": "2.2.0",
        "node-cache": "^4.2.0",
        "tiny-emitter": "1.1.0",
        "xhr2": "0.1.3"
      },
      "dependencies": {
        "js-cookie": {
          "version": "2.2.0",
          "resolved": "https://nexus.tooling.smp-paas.com/repository/npm-group/js-cookie/-/js-cookie-2.2.0.tgz",
          "integrity": "sha1-Gywnmm7s44ChIWi5JIUmWzWx7/s="
        }
      }
    },
    "@okta/okta-react": {
      "version": "3.0.8",
      "resolved": "https://nexus.tooling.smp-paas.com/repository/npm-group/@okta/okta-react/-/okta-react-3.0.8.tgz",
      "integrity": "sha512-0s5gA9mvtXrSyj6sHuqT4A+TXA89OuNIGP5hgd4vN+SpS2+K2clOt60pja2jzQ2HLhDzqW9EAwGNIheQqWqqIA==",
      "requires": {
        "@babel/runtime": "^7.11.2",
        "@okta/configuration-validation": "^0.4.1",
        "@okta/okta-auth-js": "^3.2.5"
      }
    },
```

Our build process `rm -rf node_modules` and `npm cache --force clean` then does `npm install`.

**Comment by DavidLozzi** [comment]
in addition, it does work if we just try it again, every time. When we get the error, I can jump back to the URL we wanted, and it redirects to implicit/callback and lands me back to the appropriate page. Not sure how the same code can work once and not the second time.

We also have added a hack workaround that if we get this specific error, we clear all okta tokens from the cookie, and retry the original URL. That then goes through the whole auth process and works.

**Comment by shuowu** [comment]
@DavidLozzi I tried to repro the issue with [okta react sample apps](https://github.com/okta/samples-js-react). But both `okta-hosted-signIn` and `custom-signIn` work for me with the exact versions installed (@okta/okta-react@3.0.8 and @okta/okta-auth-js@3.2.6). I assume it might be related to some storage logic in your app. 

You can try to debug the cookie and sessionStorage status with sourcemap provided from `okta-auth-js` (target file should be `token.js`, and methods should be `_addOAuthParamsToStorage` and `_getOAuthParamsStrFromStorage`)

**Comment by DavidLozzi** [comment]
@shuowu what storage logic might be in my app that could mess with this? We are using a custom token manager, with a custom setter/getter using cookies. It was shared earlier that this wouldn't be related to that. Otherwise, we don't do much else in here, unsure what to look for specifically.

Is there some documentation on how to debug this?

**Comment by aarongranick-okta** [comment]
@DavidLozzi All of our SDKs include external sourcemaps. If you are bundling with webpack, add the `source-map-loader` plugin: https://webpack.js.org/loaders/source-map-loader/ this will make the original source available for debugging in the browser. It sounds like from what you describe that there may be a concurrency issue or race condition - maybe there are multiple calls competing. The OAUTH params are read from storage here: https://github.com/okta/okta-auth-js/blob/3.2/packages/okta-auth-js/lib/token.js#L752 If this code path is done twice, it will error the second time, since it removes the OAUTH params from storage after they are read.

**Comment by estorski** [comment]
If there's anyone else interested in this, I put here how I eventually resolved all of the above.

1) the fix in `3.2.6` works indeed, but it works ONLY for non-localhost domain name address (cookies are not persisting for `localhost`, the same as session storage, so the fix does nothing in such case, refer to f.e. [this link](https://github.com/js-cookie/js-cookie/issues/486) for details);
2) to make it work in IE11 you will also need a polyfill for typed arrays (f.e. `core-js/es/typed-array`) and for webcrypto built-in lib (f.e. `webcrypto-shim`)
3) to make it work in **LOCAL** environtment you will also need to work several issues around:
  * make it a domain with at least one dot, for example `localhost.com`. You can do it by extending your `hosts` file in Windows with something like `127.0.0.1 localhost.com`;
  * if your app runs in webpack dev-server, you would also need something like `disableHostCheck: true` in its config, so that it allows for serving non-localhost domain name;
  * do not forget to update your OKTA configuration (edit application + trusted origins to allow for `localhost.com`)

Voila, after all of the above, you can finally access your local app via IE11 using the `http://localhost.com` address

**Comment by DavidLozzi** [comment]
@aarongranick-okta we're seeing this error on almost every log in now. From the code below, near the end, we're seeing the error reported by line `console.error('OKTA error 002b - redirecting to', originalUrl);` We've added error handling so when it happens we just send the user to their original url, since the access token does get set as expected. The okta libraries/code only runs once from what I've been able to determine, it's a single ReactJS app.

Sharing code below, maybe there's something in there I'm missing

Thanks!

App.js - abbreviated
```
import React, { Component, Suspense, lazy } from 'react';
...
import authService from 'redux/auth';
import { Security, SecureRoute } from '@okta/okta-react';
...
import ImplicitCallback from 'components/ImplicitCallback/ImplicitCallback';

const HomeContainer = lazy(() => import(
  /* webpackPreload: true */
  /* webpackChunkName: "chunk-Home" */
  'containers/Home/Home'));
const ResultsContainer = lazy(() => import(
  /* webpackPreload: true */
  /* webpackChunkName: "chunk-Results" */
  'containers/Results/Results'));
...

class App extends Component {
...
  render = () => {
    <Provider store={store}>
      <ConnectedRouter history={history}>
        <Security authService={authService}>
          <BrandWrapper>
            <ResponsiveWrapper>
              <ThemeProvider theme={defaultTheme}>
                <Suspense fallback={<LoadingComponent />}>
                  <Switch>
                    <SecureRoute exact path={CONFIG.UI_URL.HOME} component={HomeContainer} />
                    <SecureRoute path={CONFIG.UI_URL.RESULTS} component={ResultsContainer} />
                    ...
                    <Route path={CONFIG.OKTA.REDIRECT_URL} component={ImplicitCallback} />
                    <Route path={CONFIG.UI_URL.ERROR(':errorCode')} component={ErrorComponent} />
                    <Redirect to={CONFIG.UI_URL.ERROR_WITH_SOURCE('404')} />
                  </Switch>
                </Suspense>
              </ThemeProvider>
            </ResponsiveWrapper>
          </BrandWrapper>
        </Security>
      </ConnectedRouter>
    </Provider>

  };
}

export default App;
```

auth.js
```
import { AuthService } from '@okta/okta-react';
import { utils } from '@enrich/okta-keep-alive';
import CONFIG from 'config';
import history from './history';

export default new AuthService({
  history,
  issuer: CONFIG.OKTA.ISSUER,
  pkce: false,
  clientId: CONFIG.OKTA.CLIENT_ID,
  redirectUri: `${window.location.origin}${CONFIG.OKTA.REDIRECT_URL}`,
  tokenManager: utils.tokenManager(CONFIG.ENVIRONMENT)
});
```

utils.tokenManager
```
export const tokenManager = (env) => ({
  expireEarlySeconds: (30 * 60), // 30 mins early, we have a 24 hour expiration
  storage: {
    getItem: (key) => {
      try {
        const allCookies = Cookies.get();
        const value = {};

        Object.keys(allCookies).forEach((k) => {
          if (k.indexOf(key) === 0) {
            value[k.replace(`${key}_`, '')] = JSON.parse(allCookies[k]);
          }
        });
        return JSON.stringify(value);
      } catch (e) {
        console.error('OKTA tokenManager storage getItem', e);
        return null;
      }
    },
    setItem: (key, val) => {
      try {
        let options = { expires: 1 };
        if (env !== 'local') { // localhost has some restrictions
          options = Object.assign(options, { secure: true, domain: '.domain.com' });
        }
        const value = JSON.parse(val);

        Object.keys(value).forEach((k) => {
          const storageKey = `${key}_${k}`;
          delete value[k].value; // unncessary and makes cookie heavy
          Cookies.set(storageKey, value[k], options);
        });
      } catch (e) {
        console.error('OKTA tokenManager storage setItem', e);
      }
    }
  }
});
```

ImplicitCallback.js
```
import React, { useState } from 'react';
import { useOktaAuth } from '@okta/okta-react';
import { Redirect } from 'react-router';
import CONFIG from 'config';
import { setPsId, clearAuthCache, setAuthAttemptTime, isAuthAttemptSet, getSecondsSinceLastAttempt, clearAuthAttemptTime } from 'utils/auth/auth';

const ImplicitCallback = () => {
  const { authService, authState } = useOktaAuth();
  const [originalUrl, setOriginalUrl] = useState('');
  const authStateReady = !authState.isPending;
  const retriedInLastMin = isAuthAttemptSet() ? getSecondsSinceLastAttempt() < 60 : false;

  // okta's code in how it stores the original request URL
  const getFromUri = () => {
    const referrerKey = 'secureRouterReferrerPath';
    const location = localStorage.getItem(referrerKey) || window.location.origin;
    return location;
  };

  React.useEffect(() => {
    setOriginalUrl(getFromUri());
    setPsId();
    authService.handleAuthentication();
  }, [authService]);

  if (authStateReady && authState.error) {
    console.error('OKTA error 001 -', authState.error, 'retriedInLastMin', retriedInLastMin);

    if (authState.error.toString().toLowerCase().indexOf('match request state') > -1 && !retriedInLastMin) {
      // frustrating bug, but this code handles it when it happens
      clearAuthCache(); // deletes all cookies starting with okta-
      setAuthAttemptTime();
      console.error('OKTA error 002a - redirecting to', originalUrl);
      window.location.href = originalUrl;
      return null;
    }
    if (authState.error.toString().toLowerCase().indexOf('retrieve oauth redirect params from storage') > -1) {
      console.error('OKTA error 002b - redirecting to', originalUrl); // we are seeing a HUGE list of these errors since going live
      window.location.href = originalUrl; // this works, sends the user as expected
      return null;
    }
    clearAuthAttemptTime();
    console.error('OKTA error 003 - sending to 401', originalUrl);
    return <Redirect to={CONFIG.UI_URL.ERROR(`401/${authState.error && authState.error.toString()}`)} />;
  }

  return null;
};

export default ImplicitCallback;
```

**Comment by DavidLozzi** [comment]
@aarongranick-okta @shuowu any thoughts on the above? We created a new reactjs app, used the same token manager as above, and we're getting the same error in that app, pretty frequently.

**Comment by DavidLozzi** [comment]
I've been able to debug this some locally, no fix yet, but maybe a smoking gun for IE11

I can see the cookie is set in my browser, after _addOAuthParamsToStorage https://github.com/okta/okta-auth-js/blob/bd83f8c1c7a2727280deba1dd9da71d2ea9c6de1/lib/token.ts#L700 is run

When retrieving the cookie in _getOAuthParamsStrFromStorage, I see it does run trying to get getSessionStorage, https://github.com/okta/okta-auth-js/blob/bd83f8c1c7a2727280deba1dd9da71d2ea9c6de1/lib/token.ts#L852, but that returns null. It then gets from the cookie and that returns undefined

The get is pretty straight forward, https://github.com/okta/okta-auth-js/blob/bd83f8c1c7a2727280deba1dd9da71d2ea9c6de1/lib/browser/browserStorage.ts#L146, however, I do see this library is imported differently into this page, https://github.com/okta/okta-auth-js/blob/bd83f8c1c7a2727280deba1dd9da71d2ea9c6de1/lib/browser/browserStorage.ts#L22, in comparison to virtually everything else in this project. I wonder if the compiler isn't handling that correctly, or is another polyfill needed. I am trying to now skip that library to get a cookie and we'll see. 

Wanted to share what I'm seeing thus far.

**Comment by aarongranick-okta** [comment]
@DavidLozzi Are you embedding the signin widget into your app or are you redirecting to the Okta hosted signin page? If you are using the embedded widget you can avoid this redirect entirely

**Comment by DavidLozzi** [comment]
@aarongranick-okta we are redirecting the users to Okta, client machines are set up with SSO so they never actually see a login prompt.

**Comment by DavidLozzi** [comment]
I've added new basic HTML page just to get the cookies and see what's what. This uses `js-cookie` library and does `console.log(Cookies.get())`. Although the code is reporting the cookie is empty, it appears it's still there
![image](https://user-images.githubusercontent.com/3543383/100942745-e0d41b80-34c9-11eb-8c32-c4f6c9f2990f.png)

**Comment by DavidLozzi** [comment]
My IE11 issues have been narrowed down to IT security disabling the WinHTTP service on the laptop. With that enabled, it works (we still get the original error message on this thread) but our redirect code works. Disabling that doesn't work. We've started to push users away from IE11

**Comment by DavidLozzi** [comment]
Looking through the logs, our Edge and Chrome users have received this error (`Unable to retrieve OAuth redirect params from storage`) 3.6k times in the last 7 days. The errors start the day we released v3.0.8

![image](https://user-images.githubusercontent.com/3543383/101815799-17272180-3aee-11eb-9348-b03cb789b458.png)

I've also tried a new React App, and used v4.x of okta-react, and see the same errors there.

**Comment by droidriz** [comment]
yes chrome is still receiving this error any solution?

**Comment by pilouk** [comment]
I do have this error

**Comment by pitaman71** [comment]
Still seeing this on Chrome and Safari:

`    "@okta/okta-auth-js": "^4.6.0",
    "@okta/okta-react": "^4.1.0",
    "@okta/okta-signin-widget": "^5.2.1",
`

**Comment by hellmean** [comment]
same here
```
    "@okta/okta-auth-js": "^4.6.1",
    "@okta/okta-react": "4.1.0",
    "@okta/okta-signin-widget": "^5.3.0",
```

**Comment by hivanreyes** [comment]
I am experiencing the same issue on Chrome

    "@okta/okta-auth-js": "^4.6.0",
    "@okta/okta-react": "^4.1.0",
    "@okta/okta-signin-widget": "^4.5.2",

**Comment by swiftone** [comment]
@pitaman71, @hellmean, @hivanreyes - Can you confirm a few details for us, as we're unable to recreate this problem in testing:

- Have you removed your node_modules and reinstalled completely?  (okta-signin-widget can have a separate copy of okta-auth-js than okta-react)
- Is this happening on every login, frequently, or occasionally?
- Could you summarize your login flow in terms of routes?  (i.e. user not logged in on /, navigates to SecureRoute /secure which bounces them to unprotected /login).  That this isn't happening for all users or in our tests means that it might be related to a certain set of redirects or race conditions.

Clearly something is happening, but we need to narrow down what so we can deliver a fix.

**Comment by hellmean** [comment]
yep. can confirm, removed node_modules and yarn.lock and did complete re-install multiple times. For those users where this happens it happens on every login.

This is how the root of the application looks like:
```
      <ThemeProvider theme={theme}>
        <CssBaseline />
        <BrowserRouter>
          <Security oktaAuth={oktaAuth}>
            <Main/>
            <Route path="/implicit/callback" component={LoginCallback} />
          </Security>
        </BrowserRouter>
      </ThemeProvider>
```

**Comment by erlioniel** [comment]
Hi @swiftone,
We are experiencing the same problem with some users and have an assumption that the problem is related to a setup when Okta connected to LDAP, but a user doesn't have access to the IDP itself. In this case for us the redirect URL is smth like `/implicit/callback/?state=...&error=access_denied&error_description=User` and causes the error.
Due to the complexity of our infrastructure, it's very hard to reproduce it, but maybe someone else can try to check the assumption.

**Comment by vvsvv** [comment]
Still encouter the error:
okta-auth-js version 5.6.0
angular: 7.0.2
use implicit flow
only chrome error, ms edge is OK. 

Details:
vendor.js:formatted:66339 ERROR Error: Uncaught (in promise): AuthSdkError: Unable to retrieve OAuth redirect params from storage
AuthSdkError: Unable to retrieve OAuth redirect params from storage
    at t.value (vendor.js:93564)
    at t.value (vendor.js:93564)
    at vendor.js:93564
    at c (vendor.js:93503)
    at Generator._invoke (vendor.js:93503)
    at Generator.next (vendor.js:93503)
    at vendor.js:93564
    at new ZoneAwarePromise (polyfills.js:3272)
    at _e (vendor.js:93564)
    at Re (vendor.js:93564)
    at resolvePromise (polyfills.js:3193)
    at polyfills.js:3103
    at rejected (main.js:6476)
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke (polyfills.js:2753)
    at Object.onInvoke (vendor.js:59294)
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke (polyfills.js:2752)
    at Zone.push../node_modules/zone.js/dist/zone.js.Zone.run (polyfills.js:2512)
    at polyfills.js:3251
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (polyfills.js:2785)
    at Object.onInvokeTask (vendor.js:59285)

**Comment by Sailokeshg** [comment]
Make value of pkce:true in your okta app config and if you are using any Idp's make sure that respone_mode is set to fragment in its authorize_url

**Comment by DavidLozzi** [comment]
Same happening randomly for users. In my testing, Chrome worked, Safari errored. Here's what's being logged

```
{
  “errorSummary”:”Unable to retrieve OAuth redirect params from storage”,
  ”errorCode”:”INTERNAL”,
  ”errorLink”:”INTERNAL”,
  ”errorId”:”INTERNAL”,
  ”errorCauses”:[],
  ”name”:"AuthSdkError"
}
```
our workaround is on our error page we have a Refresh button that deletes all okta cookies and reloads the app, which then reauthenticates the user and then it works fine.

**Comment by aidandauphin** [comment]
Hi all,

I am getting this error in 2024. AuthSdkError: Unable to retrieve OAuth redirect params from storage

Please help.

Current code:
Python:
app = Flask(__name__, static_folder='./frontend/build', static_url_path='/')
app.config.update({
    'SECRET_KEY': secrets.token_hex(64),
    'SESSION_TYPE': 'filesystem',
    'SESSION_PERMANENT': False,
    'SESSION_USE_SIGNER': True,
    'SESSION_KEY_PREFIX': 'app_',
    'SESSION_FILE_DIR': './.flask_session/',
    'SESSION_COOKIE_SAMESITE': 'Lax',
    'SESSION_COOKIE_HTTPONLY': True,
    'SESSION_COOKIE_SECURE': True  # Set to True if using HTTPS
})

CORS(app, supports_credentials=True)
Session(app)

login_manager = LoginManager()
login_manager.init_app(app)

@login_manager.user_loader
def load_user(user_id):
    return User.get(user_id)

@app.route("/")
def home():
    return redirect(url_for("login"))

@app.route("/login")
def login():
    session['app_state'] = secrets.token_urlsafe(64)
    session['code_verifier'] = secrets.token_urlsafe(64)

    print("Session before redirect:", dict(session))

    hashed = hashlib.sha256(session['code_verifier'].encode('ascii')).digest()
    encoded = base64.urlsafe_b64encode(hashed)
    code_challenge = encoded.decode('ascii').strip('=')

    query_params = {
        'client_id': os.environ['CLIENT_ID'],
        'redirect_uri': "https://xxxxxx/login/callback",  ##Using NGROK
        'scope': "openid email profile",
        'state': session['app_state'],
        'code_challenge': code_challenge,
        'code_challenge_method': 'S256',
        'response_type': 'code',
        'response_mode': 'query'
    }

    request_uri = "{base_url}?{query_params}".format(
        base_url=os.environ['ORG_URL'] + "oauth2/default/v1/authorize",
        query_params=requests.compat.urlencode(query_params)
    )

    print("Redirecting to: ", request_uri)
    return redirect(request_uri)

@app.route("/login/callback")
def callback():
    print("Session in callback before checking state:", dict(session))
    
    headers = {'Content-Type': 'application/x-www-form-urlencoded'}
    code = request.args.get("code")
    app_state = request.args.get("state")

    print("Callback session data: ", dict(session))
    print(f"Received state: {app_state}")
    print(f"Expected state: {session.get('app_state')}")
    print(f"Received code: {code}")

    if app_state != session.get('app_state'):
        print(f"App state mismatch: expected {session.get('app_state')} but got {app_state}")
        return "The app state does not match", 400
    if not code:
        return "The code was not returned or is not accessible", 403

    query_params = {
        'grant_type': 'authorization_code',
        'code': code,
        'redirect_uri': "https://xxxxxx/login/callback",  # Using NGROK
        'code_verifier': session['code_verifier']
    }
    query_params = requests.compat.urlencode(query_params)
    exchange = requests.post(
        os.environ['ORG_URL'] + "oauth2/default/v1/token",
        headers=headers,
        data=query_params,
        auth=(os.environ['CLIENT_ID'], os.environ['CLIENT_SECRET']),
    ).json()

    print("Token exchange response: ", exchange)

    if not exchange.get("token_type") or exchange.get("token_type") != 'Bearer':
        return "Unsupported token type. Should be 'Bearer'.", 403
    access_token = exchange["access_token"]
    id_token = exchange["id_token"]

    userinfo_response = requests.get(os.environ['ORG_URL'] + "oauth2/default/v1/userinfo",
                                     headers={'Authorization': f'Bearer {access_token}'}).json()

    unique_id = userinfo_response["sub"]
    user_email = userinfo_response["email"]
    user_name = userinfo_response["given_name"]

    user = User(
        id_=unique_id, name=user_name, email=user_email
    )

    if not User.get(unique_id):
        User.create(unique_id, user_name, user_email)

    login_user(user)

    session.pop('app_state', None)
    session.pop('code_verifier', None)

    return send_from_directory(app.static_folder, 'index.html')

@app.route("/logout", methods=["GET", "POST"])
def logout():
    logout_user()
    return redirect(url_for("home"))

if __name__ == '__main__':
    app.run(host='0.0.0.0', port=5000, debug=True)

React app.js
import React from 'react';
import { BrowserRouter as Router, Route, Switch, useHistory } from 'react-router-dom';
import { OktaAuth, toRelativeUrl } from '@okta/okta-auth-js';
import { LoginCallback, Security } from '@okta/okta-react';
import Home from './Home';

const oktaAuth = new OktaAuth({
  issuer: 'https://xxxxxx/oauth2/default',
  clientId: '0oahy0ugq0IJw1Mdq5d7',
  redirectUri: 'https://axxxx/login/callback',
  tokenManager: {
    storage: 'localStorage'
  }
});

const App = () => {
  const history = useHistory();

  const restoreOriginalUri = async (_oktaAuth, originalUri) => {
    history.replace(toRelativeUrl(originalUri || '/', window.location.origin));
  };

  return (
    <Security oktaAuth={oktaAuth} restoreOriginalUri={restoreOriginalUri}>
      <Switch>
        <Route path="/" exact component={Home} />
        <Route path="/login/callback" component={LoginCallback} />
      </Switch>
    </Security>
  );
};

const RouterApp = () => (
  <Router>
    <App />
  </Router>
);

export default RouterApp;

**Comment by jaredperreault-okta** [comment]
@aidandauphin `okta-react` is designed for React apps to interface with the Authorization Server directly to obtain tokens. Based on your code snippets, you're interfacing with the Authorization Server from your own server (via the python code). You'll either need to

1. Remove your usage of `okta-react` and have your python server handle session management (since it's already completed the OAuth handshake)
2. Re-design your python server to no longer handle the OAuth handshake and instead validate access token coming from the react app (which will be issued directly to the react app from the Authorization Server via `okta-react`)
    a. (This is assuming your python server is also a resource server)

**Comment by aidandauphin** [comment]
Hi @jaredperreault-okta 

Really appreciate your comment, I am new to using Okta and have been struggling for a bit to get it to work. Your comment led me along the correct path and I finally got it to work.

Thanks again

Aidan
